### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by lishaduck** [ParkerH27/ToolsSite#1]
Well, what is it, @ParkerH27? And does it belong under @PSDTools?

**Comment by ParkerH27** [comment]
Had plans to link all tools here but never got to it... it is redundant now

**Comment by lishaduck** [comment]
Ahh. Do you want to move it to our namespace/delete it?

**Comment by PetalCat** [comment]
I don't know... I'm just going to leave it and figure out what to do with it later
